# Generated by Django 5.1.2 on 2024-10-27 02:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('1', 'Portão destravado pelo gancho'), ('2', 'Portão aberto remotamente'), ('4', 'Interfone tocou')], max_length=50)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.conta')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dispositivos.dispositivo')),
            ],
        ),
    ]
