# Generated by Django 5.1.2 on 2024-11-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recado',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recado',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
