# Generated by Django 5.1.2 on 2024-11-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recados', '0002_alter_recado_end_time_alter_recado_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recado',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
